# Generated by Django 4.1.1 on 2022-10-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField(max_length=30)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("chinese", "Chinese"),
                            ("korean", "Korean"),
                            ("japanese", "Japanese"),
                            ("fushion", "Fushion"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("spicy", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
