# Generated by Django 4.1.1 on 2022-10-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="address",
            field=models.CharField(default="globe", max_length=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="best",
            field=models.CharField(default="jajang", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="spicy",
            field=models.CharField(
                choices=[(1, "Baby"), (2, "Human"), (3, "Pepper")], max_length=10
            ),
        ),
    ]
