# Generated by Django 4.1.1 on 2022-10-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_restaurant_address_restaurant_best_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="restaurants",
            field=models.ManyToManyField(
                related_name="restaurant", to="restaurants.restaurant"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="spicy",
            field=models.IntegerField(
                choices=[(1, "Baby"), (2, "Human"), (3, "Pepper")]
            ),
        ),
    ]
