# Generated by Django 4.1.1 on 2022-10-17 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_restaurant_restaurants_alter_restaurant_spicy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="restaurants",
        ),
    ]
