# Generated by Django 4.1.1 on 2022-10-17 21:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_pricerange1_user_pricerange2_user_spicyok"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="egg",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, unique=True
            ),
        ),
    ]
